### ISSUE TITLE
Question in code about “Balanced KMeans”

### ISSUE THREAD

**Issue by hi-zhengcheng** [Zhang-VISLab/Learning-to-Segment-3D-Point-Clouds-in-2D-Image-Space#4]
Thanks for your nice paper and code implementation. When reading code, the following line confused me, hope you can help me out. 

This line is in the function about "Balanced KMeans for Clustering":
https://github.com/Zhang-VISLab/Learning-to-Segment-3D-Point-Clouds-in-2D-Image-Space/blob/ed31c27fb3c185ddbbae3ed4d8e4b705c47e1e7d/fun_GPGL.py#L173

```python
                # idys = np.where(mask.sum(0)<loss_mask[order])[0]
                idys_ori = order_list[:i_order]
                idys = []
                for idy in idys_ori:
                    if(flow_mat[order,idy]>=0):
                        idys.append(idy)
```

In my understanding, `idys` represents the valid clusters (valid means they can accept point from other cluster). In current implementation, `idys` is computed from `idys_ori`:

```python
idys_ori = order_list[:i_order]
``` 
Here is my question: 

1. `order_list` is computed from `loss_mask`. `loss_mask` is computed from `mask`. So at first iteration in the inner for loop, it's OK.
2. In the first iteration, point movement between clusters occurs and `mask` is updated. But `loss_mask` and `order_list` are not updated accordingly. 
3. So after first iteration, order_list is outdated and `idys_ori = order_list[:i_order]` **may find wrong candidate clusters**.

Maybe the following implementation could be more robust:
```python
idys = np.where(mask.sum(0) < CUTPOINTS_THRESHOLD)[0]
```

Thanks for your paper and code again.

**Comment by YechengLyu** [comment]
Thanks for your notice. Actually, the code block you mentioned is aimed to set up a flow direction to avoid infinite point exchange between two clusters. 

Previously, I used the code `idys = np.where(mask.sum(0) < CUTPOINTS_THRESHOLD)[0]` for cluster balancing, which resulted in infinite iterations because it consistently sending a point from set A to set B in one iteration and back from set B to set A in the next iteration. To fix this issue, I "locked" the flow direction and force set B to send points to other sets.

Hope it helps you to understand my code.

Yecheng

**Comment by hi-zhengcheng** [comment]
Thanks a lot. Nice explanation, very helpful.

**Comment by Zhang-VISLab** [comment]
Is there still any issue with the code? Please do let us know if there is any, otherwise we will close this issue. Thanks.
